apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/siddhant412/payments-api
    newTag: 4c967de3fa11f17a43464f81cb9426938215be71
